spring:
 application:
  name: Client1

server:
 port: 9082

eureka:
 instance:
  hostname: ${vcap.application.uris[0]:localhost}
  preferred-ip-address: true
  lease-renewal-interval-in-seconds: 10000
  lease-expiration-interval-in-seconds: 20
 client:
  service-url:
   defaultZone: http://localhost:10080/eureka